language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli
  - npm install
  - npm install --save-dev @angular-devkit/build-angular
  - npm i loader-runner

script:
  - ng build --prod

deploy:
  provider: heroku
  api_key: 7ece6457-b947-437e-903c-ff133e2a5c7a
  app: angular-ci-app
  skip_cleanup: true
  github_token: 9b20c8c27b586eaf77099d2d9e74aab1b2acf8e9
  local_dir: dist/angular-ci
  on:
    branch: master