language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli
  - npm install --save-dev @angular-devkit/build-angular

# before_script: # commands to run before the build step
#    - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: heroku
  api_key: ce804646-ad34-4ef1-851e-ca98a714188f
  app: angular-ci-app
  skip_cleanup: true
  github_token: 9b20c8c27b586eaf77099d2d9e74aab1b2acf8e9
  local_dir: dist/
  on:
    branch: master